### ISSUE TITLE
TEXT TRANSFORM: Slightly psychedelic background color

### ISSUE THREAD

**Issue by BenjaminHarding** [gamelab/kiwi-examples#9]
The Ben's recommend that the background colour should change in the Text Transform example. 

Ben2 recommends "Using non-harmonic sin waves on each of the three colour channels"

**Comment by BenjaminDRichards** [comment]
A suggestion:

```
MyGame.game.time.clock.setInterval( function(){ this.r = 0.5 + 0.5 * Math.sin(MyGame.game.time.clock.elapsed() * 1); this.g = 0.5 + 0.5 * Math.sin(MyGame.game.time.clock.elapsed() * 1.31); this.b = 0.5 + 0.5 * Math.sin(MyGame.game.time.clock.elapsed() * 1.157);  }, 16, MyGame.game.stage._color );
```

This suggestion does violate a private property, so it will require a little more work to be valid.

**Comment by BenjaminHarding** [comment]
Implemented
